---
- name: Setup Homebrew
  hosts: macos_host
  gather_facts: true
  vars:
    homebrew_cask_apps:
      - iterm2
      - karabiner-elements
      - maccy
      - ollama
      - podman-desktop
      - slack
      - telegram-desktop
      - visual-studio-code
    homebrew_taps:
      - robscott/tap
      - updatecli/updatecli
    homebrew_installed_packages:
      - awscli
      - chart-testing
      - checkov
      - coreutils
      - detect-secrets
      - direnv
      - docker
      - eksctl
      - flux
      - gh
      - git
      - git-delete-merged-branches
      - gnu-sed
      - grep
      - grype
      - helm
      - helm-docs
      - htop
      - httpie
      - jq
      - k9s
      - kind
      - kube-capacity
      - kubeconform
      - kubectx
      - kubernetes-cli
      - kustomize
      - maven
      - node
      - nvm
      - openjdk
      - openjdk@11
      - openjdk@17
      - podman
      - pyenv
      - python
      - rbenv
      - ruby-build
      - shellcheck
      - skopeo
      - terraform-docs
      - tfenv
      - tflint
      - tfsec
      - updatecli
      - wget
      - yamllint
      - yq
    # homebrew_uninstalled_packages: []
  roles:
    - geerlingguy.mac.homebrew
  post_tasks:
    - name: Create symbolic link for java wrapper to work
      ansible.builtin.file:
        src: /opt/homebrew/opt/openjdk@{{ item }}/libexec/openjdk.jdk
        dest: /Library/Java/JavaVirtualMachines/openjdk-{{ item }}.jdk
        state: link
      become: true
      loop:
        - 11
        - 17
        - 21
